---
name: Destroy preview environment

on:

  pull_request:
    types:
      - closed

jobs:

  environment:

    name: delete preview environment

    runs-on: ubuntu-latest

    env:

      GITHUB_ADMIN_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:

      - name: Get GitHub App token
        uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ENV_ID }}
          private-key: ${{ secrets.GH_APP_ENV_PRIVKEY }}

      - name: Delete Github preview environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ steps.get-token.outputs.token }}
          name: $GITHUB_REF_NAME
          environment: $GITHUB_REF_NAME

  worker:

    name: delete preview worker

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Remove Cloudflare worker
        run: "npm run worker -- remove --prefix $GITHUB_REF_NAME"
