---
name: Destroy preview environment

on:

  pull_request:
    types:
      - closed

jobs:

  environment:

    name: delete preview environment

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      GITHUB_USER: ${{ secrets.GH_USER }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Delete Github preview environment
        run: "npm run --silent -- project clean --environment $GITHUB_HEAD_REF"
