---
name: Create preview environment

on:

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:

  worker:

    name: deploy preview worker

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Deploy Cloudflare worker
        run: npm run worker -- deploy --prefix $env:GITHUB_REF_NAME
