---
name: Create preview environment

on:

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:

  worker:

    name: deploy preview worker

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    outputs:

      workerUrl: ${{ steps.deploy.outputs.workerUrl }}

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Deploy Cloudflare worker
        id: deploy
        run: echo "workerUrl=$(npm run --silent worker -- deploy --prefix $GITHUB_HEAD_REF)" >> "$GITHUB_OUTPUT"

      - name: Get GitHub App token
        uses: navikt/github-app-token-generator@a3831f44404199df32d8f39f7c0ad9bb8fa18b1c
        id: get-token
        with:
          app-id: ${{ secrets.GH_APP_ENV_ID }}
          private-key: ${{ secrets.GH_APP_ENV_PRIVKEY }}

      - name: Delete Github preview environment
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ steps.get-token.outputs.token }}
          name: \$GITHUB_HEAD_REF
          environment: \$GITHUB_HEAD_REF

  environment:

    needs:

      - worker

    name: create github environment

    environment:
      name: "$GITHUB_REF_NAME"
      url: "${{ needs.worker.outputs.workerUrl }}"

    runs-on: ubuntu-latest

    steps:

      - name: Debug environment creation
        run: echo "Deployed environment $GITHUB_HEAD_REF at url ${{ needs.worker.outputs.workerUrl }}"
