---
name: Publish production environment

on:

  pull_request:
    types:
      - closed
    branches:
      - master

jobs:

  worker:

    name: deploy production worker

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    outputs:

      workerEnv: ${{ steps.environment.outputs.workerEnv }}
      workerUrl: ${{ steps.deploy.outputs.workerUrl }}

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Record worker environment
        id: environment
        run: echo "workerEnv=master" >> "$GITHUB_OUTPUT"

      - name: Deploy Cloudflare worker
        id: deploy
        run: echo "workerUrl=$(npm run --silent worker -- deploy)" >> "$GITHUB_OUTPUT"

  environment:

    needs:

      - worker

    name: create github environment

    environment:
      name: "${{ needs.worker.outputs.workerEnv }}"
      url: "${{ needs.worker.outputs.workerUrl }}"

    runs-on: ubuntu-latest

    steps:

      - name: Debug environment creation
        run: echo "Deployed environment $GITHUB_HEAD_REF at url ${{ needs.worker.outputs.workerUrl }}"
