---
name: Publish environment

on:

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:

  worker:

    name: deploy worker

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      GITHUB_USER: ${{ secrets.GH_USER }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    outputs:

      workerEnv: ${{ steps.environment.outputs.workerEnv }}
      workerUrl: ${{ steps.deploy.outputs.workerUrl }}

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Record worker environment
        id: environment
        run: echo "workerEnv=$GITHUB_HEAD_REF" >> "$GITHUB_OUTPUT"

      - name: Deploy Cloudflare worker
        id: deploy
        run: npm run -- project deploy frontpage ${{ steps.environment.outputs.workerEnv }}
