---
name: Publish project

on:

  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:

  deploy:

    name: deploy project

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      GITHUB_USER: ${{ secrets.GH_USER }}
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    outputs:

      projectEnv: ${{ steps.environment.outputs.projectEnv }}
      projectUrl: ${{ steps.deploy.outputs.projectUrl }}

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Record project environment
        id: environment
        run: echo "projectEnv=$GITHUB_HEAD_REF" >> "$GITHUB_OUTPUT"

      - name: Deploy project
        id: deploy
        run: echo "projectUrl=$(npm run --silent -- project deploy frontpage ${{ steps.environment.outputs.projectEnv }})" >> "$GITHUB_OUTPUT"

      - name: Debug project url
        run: echo ${{ steps.deploy.outputs.projectUrl }}

  environment:

    needs:

      - deploy

    name: create github environment

    environment:
      name: "${{ needs.deploy.outputs.projectEnv }}"
      url: "${{ needs.deploy.outputs.projectUrl }}"

    runs-on: ubuntu-latest

    steps:

      - name: Debug environment creation
        run: echo "Deployed environment $GITHUB_HEAD_REF at url ${{ needs.deploy.outputs.projectUrl }}"
