---
name: Run NPM tests

on:

  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:

  test:

    name: test

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install playwright browsers
        run: npm exec playwright install

      - name: Lint code
        run: npm run lint

      - name: Test project
        run: npm run test
