---
name: Undeploy preview environment

on:

  pull_request:
    types:
      - closed

jobs:

  environment:

    name: delete preview environment

    runs-on: ubuntu-latest

    env:

      GITHUB_ADMIN_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:

      - uses: strumwolf/delete-deployment-environment@v2
        with:
          token: $GITHUB_ADMIN_TOKEN
          environment: $GITHUB_REF_NAME

  worker:

    name: delete preview worker

    runs-on: ubuntu-latest

    env:

      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

    steps:

      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Remove Cloudflare worker
        run: npm run worker -- remove --verbose --prefix $GITHUB_REF_NAME
